# Generated by Django 4.0.4 on 2022-05-21 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_remove_favorites_user_favorites_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
    ]
