# Generated by Django 4.0.4 on 2022-05-21 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_messages_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-date'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
    ]
