# Generated by Django 4.0.3 on 2022-03-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siginUP', '0002_account_delete_signupmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
