# Generated by Django 4.0.2 on 2022-03-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_name', models.CharField(max_length=55)),
                ('q_ans', models.CharField(max_length=3000)),
            ],
        ),
    ]
