# Generated by Django 4.0.4 on 2022-05-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['q_name'], 'verbose_name': 'question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterField(
            model_name='questions',
            name='q_ans',
            field=models.CharField(max_length=3000, verbose_name='Answer'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q_name',
            field=models.CharField(max_length=55, verbose_name='Question'),
        ),
    ]
