# Generated by Django 4.0.2 on 2022-03-27 10:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0003_alter_cmsslider_cms_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
