# Generated by Django 4.0.3 on 2022-03-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siginUP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=65)),
                ('phone', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='SignUpModel',
        ),
    ]
