# Generated by Django 4.0.3 on 2022-03-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
