# Generated by Django 4.0.1 on 2022-03-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siginUP', '0003_account_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(default='False', max_length=10),
        ),
    ]
