# Generated by Django 4.0.1 on 2022-03-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('description', models.CharField(default='', max_length=10000)),
                ('username', models.CharField(default='Guest', max_length=32)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
