# Generated by Django 4.0.1 on 2022-03-29 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_alter_feedbackmodel_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='author',
        ),
    ]
