# Generated by Django 4.0.1 on 2022-04-05 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_feedbackmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Guest', max_length=40)),
                ('caption', models.TextField(default='Empty')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
