# Generated by Django 4.0.1 on 2022-03-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_order_order_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_img',
            field=models.ImageField(null=True, upload_to='order_img/'),
        ),
    ]
