# Generated by Django 4.0.2 on 2022-02-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advt_dt', models.DateTimeField(auto_now=True)),
                ('advt_name', models.CharField(max_length=200, verbose_name='Advertisement name')),
                ('advt_img', models.ImageField(upload_to='adver/')),
                ('advt_price', models.CharField(max_length=100, verbose_name='Price')),
                ('advt_link', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
    ]
