# Generated by Django 4.0.2 on 2022-04-22 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('image', models.ImageField(null=True, upload_to='static/img/category')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Advt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_date_created', models.DateField(auto_now=True, null=True)),
                ('advertisement_name', models.CharField(max_length=200, verbose_name='Advertisement name')),
                ('advertisement_image', models.ImageField(null=True, upload_to='media/adver/')),
                ('advertisement_price', models.IntegerField(null=True, verbose_name='Price')),
                ('advertisement_description', models.TextField(default='', max_length=1000)),
                ('advertisement_favourites', models.IntegerField(default=0)),
                ('advertisement_location', models.CharField(default='Алматы', max_length=30)),
                ('advertisement_view', models.IntegerField(default=0)),
                ('advertisement_slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('advertisement_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grid_panel.category', verbose_name='category')),
                ('advertisement_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
    ]
