# Generated by Django 4.0.2 on 2022-03-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advt_host_id', models.IntegerField(default=1)),
                ('advt_item_id', models.IntegerField(default=-1)),
                ('advt_date_created', models.DateField(auto_now=True)),
                ('advt_type', models.CharField(default='Другие', max_length=100)),
                ('advt_name', models.CharField(max_length=200, verbose_name='Advertisement name')),
                ('advt_img', models.ImageField(upload_to='adver/')),
                ('advt_price', models.CharField(max_length=100, verbose_name='Price')),
                ('advt_link', models.CharField(max_length=200, null=True)),
                ('advt_description', models.CharField(default='', max_length=1000)),
                ('advt_favourite', models.IntegerField(default=0)),
                ('advt_views', models.IntegerField(default=0)),
                ('advt_location', models.CharField(default='Алматы', max_length=30)),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
    ]
