# Generated by Django 4.0.1 on 2022-03-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advt',
            name='advt_location',
            field=models.CharField(default='Алматы', max_length=30),
        ),
    ]
