# Generated by Django 4.0.2 on 2022-05-09 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grid_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advt',
            name='advertisement_date_created',
            field=models.DateField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
