# Generated by Django 4.0.1 on 2022-03-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_panel', '0002_advt_advt_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='advt',
            name='advt_date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='advt',
            name='advt_host_id',
            field=models.IntegerField(default=1),
        ),
    ]
