# Generated by Django 4.0.2 on 2022-05-17 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid_panel', '0002_alter_advt_advertisement_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advt',
            name='advertisement_slug',
        ),
    ]
