# Generated by Django 4.0.4 on 2022-05-21 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grid_panel', '0003_remove_advt_advertisement_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advt',
            options={'ordering': ['-advertisement_date_created'], 'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-pk'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='advt',
            name='advertisement_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='grid_panel.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='advt',
            name='advertisement_date_created',
            field=models.DateField(auto_now=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='advt',
            name='advertisement_description',
            field=models.TextField(default='', max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='advt',
            name='advertisement_favourites',
            field=models.IntegerField(default=0, verbose_name='Favourites'),
        ),
        migrations.AlterField(
            model_name='advt',
            name='advertisement_image',
            field=models.ImageField(null=True, upload_to='media/adver/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='advt',
            name='advertisement_location',
            field=models.CharField(default='Алматы', max_length=30, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='advt',
            name='advertisement_name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='advt',
            name='advertisement_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img/category', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Category name'),
        ),
    ]
