# Generated by Django 4.0.1 on 2022-03-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_panel', '0003_advt_advt_date_created_advt_advt_host_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='advt',
            name='type',
            field=models.CharField(default='Другие', max_length=100),
        ),
    ]
