# Generated by Django 4.0.1 on 2022-03-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_panel', '0004_advt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='advt',
            name='advt_description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='advt',
            name='advt_favourite',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advt',
            name='advt_views',
            field=models.IntegerField(default=0),
        ),
    ]
