# Generated by Django 4.0.2 on 2022-04-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_panel', '0004_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advt',
            name='advt_price',
            field=models.IntegerField(max_length=100, verbose_name='Price'),
        ),
    ]
