# Generated by Django 4.0.1 on 2022-03-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_panel', '0005_advt_advt_description_advt_advt_favourite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advt',
            old_name='type',
            new_name='advt_type',
        ),
        migrations.AddField(
            model_name='advt',
            name='advt_item_id',
            field=models.IntegerField(default=-1),
        ),
    ]
