# Generated by Django 4.0.1 on 2022-03-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid_panel', '0006_rename_type_advt_advt_type_advt_advt_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advt',
            name='advt_dt',
        ),
    ]
