# Generated by Django 4.0.4 on 2022-04-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_panel', '0006_rename_advt_cat_advt_advertisement_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advt',
            name='advertisement_view',
            field=models.IntegerField(default=0),
        ),
    ]
