# Generated by Django 4.0.2 on 2022-03-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('ad_img', models.ImageField(upload_to='order_img/')),
            ],
        ),
    ]
