# Generated by Django 4.0.2 on 2022-04-10 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applyAd', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
