# Generated by Django 4.0.2 on 2022-03-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applyAd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
