# Generated by Django 4.0.4 on 2022-05-21 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
