# Generated by Django 4.0.2 on 2022-04-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid_panel', '0006_rename_advt_cat_advt_advertisement_category_and_more'),
        ('myProfile', '0002_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fav_adver',
            field=models.ManyToManyField(to='grid_panel.Advt'),
        ),
    ]
