# Generated by Django 4.0.3 on 2022-03-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myProfile', '0005_alter_profile_avatar_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_images/default_avatar.png', upload_to='profile_images'),
        ),
    ]
